drop database if exists desafio;
create database desafio;

use desafio;

CREATE TABLE tb_responsavel_projeto (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(10) NOT NULL
);

INSERT INTO tb_responsavel_projeto VALUES (null,'ADMFIN'), (null,'ADMPLN'), (null,'ADMAPO');

CREATE TABLE tb_projetos (
	ID INT  PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_TERMINO DATE NOT NULL,
    STATUS ENUM('PLANEJADO', 'EM EXECUÇÃO', 'ABORTADO', 'FINALIZADO') NOT NULL,
	ID_RESPONSAVEL INT NOT NULL,
    FOREIGN KEY (ID_RESPONSAVEL) REFERENCES tb_responsavel_projeto(ID)
);


CREATE TABLE tb_responsavel_tarefa(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(5) NOT NULL
);
INSERT INTO tb_responsavel_tarefa VALUES (null ,'PLO'), (null, 'GFU'), (null, 'CTB'), (null, 'GBP');

CREATE TABLE tb_tarefas(
	ID INT PRIMARY KEY AUTO_INCREMENT,
	TITULO VARCHAR(25) NOT NULL,
    DESCRICAO VARCHAR(100),
    PRAZO INT NOT NULL,
    STATUS ENUM('PLANEJADO', 'EM EXECUÇÃO', 'ABORTADO', 'FINALIZADO') NOT NULL,
    ID_RESPONSAVEL INT NOT NULL,
    ID_PROJETO INT NOT NULL,
    FOREIGN KEY (ID_RESPONSAVEL) REFERENCES tb_responsavel_tarefa(ID),
    FOREIGN KEY (ID_PROJETO) REFERENCES tb_projetos(ID)
);



CREATE TABLE USER(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(50) NOT NULL UNIQUE,
    SENHA VARCHAR(300) NOT NULL
    
);

INSERT INTO USER VALUES(null,'matheus','$2a$10$XBRZyobS/.g2NNARDUSTDu8cMAvq9GOYESCrFQzsum9BYQf6uf19e');
